# for IP `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgres_db`
services:
  postgresql:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_PASSWORD: root
    ports:
      - 5432:5432 # Postgres on localhost:5432
    networks:
      - postgres
    volumes:
      - pgdata:/home/harsh/Documents/PostgresDB
    labels:
      - createdBy=DevBox
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8888:80" # PgAdmin on localhost:8888
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - postgres
    volumes:
      - pgadmin-data:/home/harsh/Documents/PostgresDB
    labels:
      - createdBy=DevBox
networks:
  postgres:
    driver: bridge
volumes:
  pgdata:
  pgadmin-data:
