version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.2
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    container_name: sn-zookeeper
  kafka:
    image: confluentinc/cp-kafka:7.5.2
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    container_name: sn-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    depends_on: 
      - postgresql
    ports:
      - 8888:80 # PgAdmin on localhost:8888
    environment:
      PGADMIN_DEFAULT_EMAIL: amanupadhyay2004@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/home/harsh/Desktop/ordering-app
  postgresql:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_PASSWORD: root
    ports:
      - 5432:5432 # Postgres on localhost:5432
    volumes:
      - pgdata:/home/harsh/Desktop/ordering-app
volumes:
  pgdata:
  pgadmin-data:
